### ISSUE TITLE
make install fails due to missing pass.fish-completion

### ISSUE THREAD

**Issue by nickzana** [FiloSottile/passage#10]
Running `make install` errors with:
```
install: cannot stat 'src/completion/pass.fish-completion': No such file or directory
```
`src/completion/pass.fish-completion` was deleted in a previous commit. If dropping fish support was intentional, I think references to the completion need to be removed from the Makefile.

**Comment by FiloSottile** [comment]
Not strictly intentional but I don't know fish enough to patch it and test it, so yeah good catch.
