### ISSUE TITLE
Implement `init` for re-keying

### ISSUE THREAD

**Issue by decentral1se** [FiloSottile/passage#13]
:wave: 

It's possible to work around this but it does make things more inconvenient.

**Comment by FiloSottile** [comment]
Hi! What part of init do you need? The fresh repo setup or the existing repo/folder re-encryption functionality? The former is trivial, I remember the latter being tricky somehow.

**Comment by decentral1se** [comment]
So, the two things, I believe: fresh init which allows to specify identities & re-encrypt.

The fresh init case is used day-to-day for personal stores within the directory hierarchy.

The re-encrypt is used to onboarding new folks into the team store. You "re-key" the entire thing with the new identity.

**Comment by Myridium** [comment]
Well a reference to `cmd_init` is still floating around in the source for some reason. This is meant for `pass init` or `passage init`.

**Comment by MarkusZoppelt** [comment]
You **could** do a re-keying after changing your `.age-recipients` with a simple `zsh` script:

```zsh
cd $HOME/.passage/store
for file in **/*.age
passage mv ${file:r} ${file:r}
```

**_However_**, this is very tedious because it will ask you for a PIN and requires a physical touch **for every entry**.

**Comment by FiloSottile** [comment]
Done by #46
