### ISSUE TITLE
Unecessary prompt for password

### ISSUE THREAD

**Issue by Myridium** [FiloSottile/passage#16]
When editing a password, `passage` prompts for the password once to decrypt the file. But then it asks again when saving the file. It should not need to prompt the second time.  
```
$ passage edit tmp
Enter passphrase for identity file "/home/username/.passage/identities":
Enter passphrase for identity file "/home/username/.passage/identities":
Password unchanged.
```

**Comment by Myridium** [comment]
The problem is that the existing file is decrypted (again) to check whether it has changed.

https://github.com/FiloSottile/passage/blob/1262d308f09db9b243513a428ab4b8fb1c30d31d/src/password-store.sh#L409-L416

**Comment by FiloSottile** [comment]
This is an intentional design choice of password-store, presumably to catch conflicts that happen during editing, which I don't think I am going to deviate from in passage.
