### ISSUE TITLE
`ctrl+C` during password prompt leaves terminal unusable

### ISSUE THREAD

**Issue by Myridium** [FiloSottile/passage#17]
Type `passage edit tmp`, then press `ctrl+C` during the password prompt. Now, no characters show in the terminal when typing further commands.

**Comment by sthagen** [comment]
Interesting. Does issuing `reset` fix that?

**Comment by Myridium** [comment]
Yes, issuing `reset` fixes it.

**Comment by Myridium** [comment]
Actually, I'm not sure what you mean. I have an executable called `reset` on path, but it's provided by `anaconda` (Python). So I think it's unrelated to what you're asking. What do you mean by issuing `reset`?

**Comment by sthagen** [comment]
> Actually, I'm not sure what you mean. I have an executable called `reset` on path, but it's provided by `anaconda` (Python). So I think it's unrelated to what you're asking. What do you mean by issuing `reset`?

I meant [terminal initialization](https://linux.die.net/man/1/reset) which also works on my macOS terminals.

**Comment by Myridium** [comment]
Yes okay, a `reset` does fix it.

**Comment by FiloSottile** [comment]
I believe this should be fixed in age v1.1.0+. If not, please open an issue at https://github.com/FiloSottile/age.
