### ISSUE TITLE
There is no support for `pinentry`.

### ISSUE THREAD

**Issue by Myridium** [FiloSottile/passage#18]
In `pass`, the `gpg-agent` manages the secret associated with the GPG key. This may be the PIN to access a YubiKey, or the passphrase to a password-protected GPG identity file. 

On the other hand, `passage` prompts for the password to the `age` private key every time it is needed. This program should either hand-off the secret-gathering to another program (like an `age-plugin-...` or `ssh-agent` or something) or it should support the use of a chosen `pinentry` program.

**Comment by FiloSottile** [comment]
Caching a passphrase is covered by #3. Caching the YubiKey PIN is going to be available through an upcoming `age-plugin-yubikey-agent` that uses https://github.com/FiloSottile/yubikey-agent. I have no plans to implement actual Pinentry support at the moment, as the UX is actually pretty poor on macOS and Windows.
