### ISSUE TITLE
Feature Request/Question - encrypt recipient file

### ISSUE THREAD

**Issue by stsch9** [FiloSottile/passage#25]
To share passwords with others, it makes sense to store the data on a shared storage. The shared storage might not be very trusted (e.g. Google Drive).
One problem is to share the recipient file securely with others.
Would it make sense to encrypt the recipient file also for all recipients with the recipient keys of the recipient file and put it on the shared storage? If so, would it make sense to add in passage a command e.g. "encrypt_recipient_file" or an env variable e.g. "ENCRYPT_RECIPIENT_FILE=true"?

**Comment by FiloSottile** [comment]
That's interesting, but it would make every write operation require a decryption. Instead, I suggest putting the file outside the synced folder and pointing `$PASSAGE_RECIPIENTS_FILE` to it.
