### ISSUE TITLE
Passage requiring first entry of .age-recipients for decryption

### ISSUE THREAD

**Issue by solomon-b** [FiloSottile/passage#31]
I've setup three Yubikeys with Age and configured passage to use them by running once for each yubikey:
```bash
➜ age-plugin-yubikey --identity >> $HOME/.passage/identities
➜ age-plugin-yubikey --list >> $HOME/.passage/store/.age-recipients
```

 I then generated a test password and am only able to decrypt it with the first yubikey I added to the `.age-recipients` file:

```bash
➜ passage test/pass               
Please insert YubiKey with serial 19234119: (y/n) 
```

**Comment by solomon-b** [comment]
I noticed issue #7 addresses my question. The expected behavior should be that after a timeout I am able to use the alternate key(s) however, `passage` is sitting at this prompt:

```
passage test
Please insert YubiKey with serial 22388305: (y/n) Waiting for ⁨age-plugin-yubikey⁩...
```

**Comment by surmeier** [comment]
I think passage is great but it seems to be designed entirely around 1 machine with 1 key which is unfortunate. Ideally it would be trivial to have the password repository on multiple machines, each with their own yubikey (i.e. each connected to a 5C nano).

**Comment by FiloSottile** [comment]
> have the password repository on multiple machines, each with their own yubikey

This is totally doable: on each machine you use a different identities file listing its associated YubiKey, and you put all recipients in the recipient file.

What I think @solomon-b is trying to do is to have multiple YubiKeys listed in the same identities file on the same machine. That will try them in order, but should work. What happens if you type `n` at the `(y/n)` prompt? What version of age are you using?

**Comment by surmeier** [comment]
Hmm, I tried that before and it didn't work, so I assumed it wasn't possible. I will create another issue to avoid confusion.

**Comment by solomon-b** [comment]
@FiloSottile Sorry for the extremely slow response. It re-prompts me for the same key again:
```
➜ passage service/bitwarden/master
Please insert YubiKey with serial 22388305: (y/n) n
Please insert YubiKey with serial 22388305: (y/n) n
Please insert YubiKey with serial 22388305: (y/n) n
Please insert YubiKey with serial 22388305: (y/n) 
```

I'm using `rage`:
```
➜ rage --version
rage 0.9.1
```

**Comment by solomon-b** [comment]
It has been a while since I tried out `passage` and I'm finally getting back to it.

This issue came up while trying to emulate @FiloSottile's setup in their original blog post:

> Secrets are encrypted to two keys generated on two YubiKeys with the default settings of age-plugin-yubikey. These keys can’t be extracted or cracked by any attacker, regardless of how compromised my laptop or vault gets. One YubiKey is a USB-C Nano that lives in my laptop, the other one lives on my keychain. If (when!) one breaks, I can use the other to re-encrypt all files to the replacement.

I'm realizing now that even if `passage` only wants to prompt for the first identity in the `identities` file, you can simply use `age` directly to decrypt with a specific alternate identity:

```
$ rage -d -i ~/.passage/BW1-yubikey.identity master.age
Enter PIN for YubiKey with serial 123456789: 
Waiting for ⁨age-plugin-yubikey⁩...
XXXXXX
```

I hope this comment helps anyone else that was confused here.
