### ISSUE TITLE
macOS/Homebrew installation fails

### ISSUE THREAD

**Issue by telemachus** [FiloSottile/passage#4]
Because the repo does not yet have any tagged commits, [the current instructions](https://github.com/FiloSottile/passage/blob/main/INSTALL#L7-L10) lead to an error though the rest of the steps continue.

```shell
fatal: No names found, cannot describe anything. # this is the error from git describe --tags
install: mkdir /usr/local/Cellar/passage
install: mkdir /usr/local/Cellar/passage//lib
install: mkdir /usr/local/Cellar/passage//lib/passage
install: src/platform/darwin.sh -> /usr/local/Cellar/passage//lib/passage/platform.sh
install: mkdir /usr/local/Cellar/passage//lib/passage/extensions
install: mkdir /usr/local/Cellar/passage//bin
install: src/.passage -> /usr/local/Cellar/passage//bin/passage
```

`brew link passage` doesn't work after that, presumably because `brew` expects installations to be in a tagged subfolder.

```shell
$ brew link passage
Linking /usr/local/Cellar/passage/lib... 0 symlinks created.
```

Running the commands with a manual tag works fine. E.g., `make install PREFIX="$(brew --cellar)/passage/0.0.1"`

No need to do anything since I'm assuming that this is still relatively alpha and you're not ready to tag anything yet. But I figured I would put this here for anyone else who has this problem.

**Comment by FiloSottile** [comment]
Ah yep, this is because I was installing from a repo where I had forked password-store, and git tags are not namespaced (which always felt like a major design flaw). Fixed!
