### ISSUE TITLE
I don't use homebew, but instead, I use ports on the mac. "make install" gives errors

### ISSUE THREAD

**Issue by wglb** [FiloSottile/passage#41]
sudo make install
Password:
install: chmod 755 /usr/share/zsh/site-functions: Operation not permitted
install: /usr/share/zsh/site-functions/_passage: Operation not permitted
make: *** [install-common] Error 71

**Comment by surmeier** [comment]
You can get around this by changing the `prefix` variable in the makefile to `/usr/local/`. If you use something like `fzf` then you can remove the section for shell autocompletion.

**Comment by wglb** [comment]
That fixes the problem, thanks.
