### ISSUE TITLE
Unclear how to setup multiple yubikeys on different machines

### ISSUE THREAD

**Issue by surmeier** [FiloSottile/passage#42]
I am trying to have a yubikey on each machine so that 1 key is listed in the `identities` file and every key listed in `.age-recipients` which is in the git repository. 

After generating a new key on a new machine, I add that key to `.age-recipients` on the machine that already has an established key in `identities` and `.age-recipients`. Then I do the following on the new machine:

```
age-plugin-yubikey --identity > $HOME/.passage/identities
git clone password-repo ~$HOME/.passage/store/
pass Example
```

This obviously fails to work because I did not re-encrypt the repository, but `init` is not implemented. Do I just have to copy each file again so it is re-encrypted with both keys?

**Comment by surmeier** [comment]
This is just a duplicate of #13 in a different context. Closing

**Comment by FiloSottile** [comment]
Ah yep, re-encryption is the main missing piece. I want to build some affordances around it to make it easier, at the very least not having to type the PIN for every secret.
