### ISSUE TITLE
zsh-specific code in "Migrating from pass" instructions

### ISSUE THREAD

**Issue by telemachus** [FiloSottile/passage#5]
Sorry, but another little gotcha: [the README's instructions to migrate from pass](https://github.com/FiloSottile/passage/blob/main/README#L59-L70) are zsh specific.

In particular, `name="${${passfile#./}%.gpg}"` doesn't work on bash. You need to do
that in two steps for bash.

Maybe just add that those instructions are an example for zsh users and that bash users
should edit accordingly?

For what it's worth, I used the following for bash:

```bash
set -o pipefail
cd "${PASSWORD_STORE_DIR:-$HOME/.password-store}" || exit
while read -r -d "" passfile
do
	name="${passfile#./}"
	name="${name%.gpg}"
	[[ -f "${PASSAGE_DIR:-$HOME/.passage/store}/$name.age" ]] && continue
	pass "$name" | passage insert -m "$name" || { passage rm "$name"; break; }
done < <(find . -path '*/.git' -prune -o -iname '*.gpg' -print0)
```

**Comment by FiloSottile** [comment]
Thank you! I updated it, definitely want it to work with bash.
